skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solutio = "5cmBDMRdqAfrhmkMmLVxTBCNBHxh5sneyvWXJViyjz9E"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
