skip_local_validator = true

[toolchain]

[features]
remarjann = true
skip-lint = false

[programs.localnet]
marjan = "5cmBDMRdqAfrhmkMmLVxTBCNBHxh5sneyvWXJViyjz9E"

[programs.devnet]
marjan = "5cmBDMRdqAfrhmkMmLVxTBCNBHxh5sneyvWXJViyjz9E"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
