"""Renders the framework's knowledge into Markdown under docs/framework/.

    python -m marjan_framework            # all reports
    python -m marjan_framework rules      # one report: rules | evidence | scenarios | economics
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from . import economics, scenarios

HERE = Path(__file__).resolve().parent
OUT = HERE.parent.parent / "docs" / "framework"
GENERATED = "<!-- Generated by `python -m marjan_framework`. Edit the JSON/Python sources, not this file. -->\n\n"

LEVEL_ORDER = ["global", "eu", "national", "state", "municipal", "field"]
LEVEL_NAME = {"global": "Global", "eu": "European Union", "national": "Brazil (national)", "state": "State (Alagoas)",
              "municipal": "Municipal", "field": "Field (founder's anonymized operational knowledge)"}


def load(name: str) -> dict:
    return json.loads((HERE / name).read_text())


def brl(x: float) -> str:
    if x >= 1e9:
        return f"R$ {x / 1e9:,.2f} bn"
    if x >= 1e6:
        return f"R$ {x / 1e6:,.2f} M"
    return f"R$ {x:,.0f}"


def render_rules() -> str:
    rb = load("rulebook.json")
    lines = [GENERATED, "# Rulebook\n",
             "Each business rule states what Marjan enforces, the legal or institutional source, how it shows up in practice, "
             "and where it is enforced.\n", "| Level | Meaning |", "| --- | --- |"]
    lines += [f"| `{k}` | {v} |" for k, v in rb["enforcement_levels"].items()]
    for domain, title in (("procurement", "Shared purchasing instruments"), ("payment", "Payment obligations and financing")):
        lines += [f"\n## {title}\n"]
        for r in (r for r in rb["rules"] if r["domain"] == domain):
            lines += [f"### {r['id']} · {r['title']}  \n`{r['jurisdiction']}` · enforcement: **{r['enforcement']}**\n",
                      r["rule"] + "\n", "**Sources:** " + "; ".join(r["sources"]) + "\n"]
            if r["practice"]:
                lines.append(f"**Practice:** {r['practice']}\n")
            lines.append(f"**Code:** `{r['code']}`\n")
    return "\n".join(lines)


def render_evidence() -> str:
    ev = load("evidence.json")
    lines = [GENERATED, "# Evidence base\n",
             "Every claim used in the pitch and documentation, with its status and source. "
             "Allegations are labeled as such; nothing here is presented as proven unless a court, law or official dataset says so.\n",
             "| Status | Meaning |", "| --- | --- |"]
    lines += [f"| `{k}` | {v} |" for k, v in ev["status_legend"].items()]
    for level in LEVEL_ORDER:
        items = [i for i in ev["items"] if i["level"] == level]
        if not items:
            continue
        lines += [f"\n## {LEVEL_NAME[level]}\n", "| ID | Claim | Status | Date | Source |", "| --- | --- | --- | --- | --- |"]
        for i in items:
            src = f"[{i['source']}]({i['url']})" if i["url"] else i["source"]
            lines.append(f"| `{i['id']}` | {i['claim']} | {i['status']} | {i['date']} | {src} |")
    return "\n".join(lines)


def _d(d) -> str:
    if d is None:
        return "—"
    return ("✅ " if d.ok else f"⛔ `{d.rule}` ") + d.reason


def render_scenarios() -> str:
    lines = [GENERATED, "# Scenario replays\n",
             "Documented cases replayed through the rules. Where a defect was documented, the same sequence runs under an "
             "illustrative legacy control and under Marjan. Quantities are normalized unless the source gives figures.\n"]
    for s in scenarios.run_all():
        lines += [f"## {s.id} · {s.title}\n", f"*Level:* {LEVEL_NAME[s.level]} · *Evidence:* " +
                  ", ".join(f"`{e}`" for e in s.evidence) + "\n", f"**Question.** {s.question}\n"]
        has_legacy = any(st.legacy is not None for st in s.steps)
        if has_legacy:
            lines += ["| Step | Legacy control | Marjan |", "| --- | --- | --- |"]
            lines += [f"| {st.action} | {_d(st.legacy)} | {_d(st.marjan)} |" for st in s.steps]
        else:
            lines += ["| Step | Marjan |", "| --- | --- |"]
            lines += [f"| {st.action} | {_d(st.marjan)} |" for st in s.steps]
        lines += ["", f"**Finding.** {s.finding}\n"]
    return "\n".join(lines)


def render_economics() -> str:
    a = economics.load_assumptions()
    costs = economics.load_costs()
    lc = economics.lifecycle_costs(costs)
    fx = a["fx"]["brl_per_usd"]["value"]
    modes = [m for m in ("no_close", "measured_close", "fees_only") if m != "measured_close" or "closing" in lc]
    lines = [GENERATED, "# Unit economics and scalability\n",
             "This page separates three kinds of numbers. **Measured**: fees, rent deposits and refunds read back from the "
             f"{len(costs['steps'])} devnet transactions in [`docs/DEVNET.md`](../DEVNET.md) (`client/devnet-costs.json`). "
             "**Conditional**: costs that depend on a design choice, stated as such. **Hypothesis**: prices, volumes and "
             "adoption from `framework/marjan_framework/assumptions.json`, not validated with any buyer. Devnet charges the "
             "same base fee per signature as mainnet; priority fees are excluded.\n",
             "## Measured cost per lifecycle\n",
             "| Lifecycle | Transactions | Fees (lamports) | Rent, net (lamports) | Compute units |", "| --- | --- | --- | --- | --- |"]
    for v in lc.values():
        lines.append(f"| {v.name} | {v.transactions} | {v.fee_lamports:,} | {v.rent_lamports:,} | {v.compute_units:,} |")
    lines += ["\nRent is a refundable deposit, not a fee. A negative value is rent returned when an account is closed.\n",
              "## Cost per obligation (one adhesion + one financed obligation), in BRL\n",
              f"Assumed BRL/USD: {fx}. Modes: " + "; ".join(f"**{m}** = {economics.MODES[m]}" for m in modes) + ".\n",
              "| SOL price (USD) | " + " | ".join(modes) + " |", "| --- |" + " --- |" * len(modes)]
    for usd in a["fx"]["usd_per_sol"]["sensitivity"]:
        lines.append(f"| {usd} | " + " | ".join(f"R$ {economics.cost_per_obligation_brl(usd, m):.3f}" for m in modes) + " |")
    for m in modes:
        lines += [f"\n## Scenarios · {economics.MODES[m]}\n",
                  "| Scenario | Volume through Marjan | Obligations/yr | Avg tx/s | Financed volume | Revenue (hypothesis) | On-chain cost | Cost / revenue |",
                  "| --- | --- | --- | --- | --- | --- | --- | --- |"]
        for r in economics.scenarios(mode=m):
            lines.append(f"| {r['scenario']} | {brl(r['volume_brl'])} | {r['obligations_per_year']:,.0f} | {r['tx_per_second_avg']:.3f} | "
                         f"{brl(r['financed_volume_brl'])} | {brl(r['revenue_brl'])} | {brl(r['chain_cost_brl'])} | "
                         f"{100 * r['chain_cost_share_of_revenue']:.1f}% |")
    p = a["pricing"]
    gross = economics.per_obligation_lamports(lc, "no_close")
    fees = economics.per_obligation_lamports(lc, "fees_only")
    findings = [
        "\n## Revenue model (hypothesis)\n",
        f"- Public bodies pay **nothing**. {p['government_fee_brl']['why']}",
        f"- Financiers pay a verification fee of R$ {p['verification_fee_brl_per_check']['value']:.2f} per check, "
        f"{p['checks_per_financed_obligation']['value']} checks per financed obligation.",
        f"- A take rate of {10_000 * p['take_rate_on_financed_volume']['value']:.0f} bps on financed volume, shared with a licensed financing partner. "
        "Benchmark: the federal AntecipaGov charges lenders 0.17%-0.42% per operation (Portaria SEGES/MGI 6.521/2025).",
        "\n## What the numbers say\n",
        "1. **Throughput is not the constraint.** Even the national scenario averages well under one transaction per second. The binding "
        "constraint is per-account write serialization, which is exactly what enforces the caps (see the concurrency run in DEVNET.md).",
        f"2. **Rent dominates on-chain cost.** Rent deposits are {100 * (gross - fees) / gross:.1f}% of the gross cost per obligation.",
    ]
    if "closing" in lc:
        closed = economics.per_obligation_lamports(lc, "measured_close")
        findings.append(
            f"3. **Closing recovers part of it, not all.** The implemented close instructions return {100 * (gross - closed) / gross:.0f}% of the "
            "gross cost. The rest stays on purpose: fiscal-document markers stop an invoice from backing a second obligation, and executed "
            "adhesions are the provenance that obligations cite. Going further needs a design change (smaller markers, or compression), not a parameter.")
    findings.append(
        f"{4 if 'closing' in lc else 3}. **The cheapest lever is when to record, not how.** The scenarios record every obligation on-chain but "
        "earn revenue only on the financed share. Recording an obligation when its supplier asks for financing (and keeping the free "
        "compliance layer for adhesions) spreads the same cost over revenue-bearing obligations only.")
    findings.append(
        f"{5 if 'closing' in lc else 4}. **Revenue is a hypothesis.** The compliance layer is free for government; whether financiers pay the "
        "assumed fee and take rate is the open question in docs/THESIS.md (H5, H8).")
    return "\n".join(lines + findings)


RENDERERS = {"rules": ("RULEBOOK.md", render_rules), "evidence": ("EVIDENCE.md", render_evidence),
             "scenarios": ("SCENARIOS.md", render_scenarios), "economics": ("ECONOMICS.md", render_economics)}


def main(argv: list[str]) -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    names = argv or list(RENDERERS)
    for n in names:
        fname, fn = RENDERERS[n]
        (OUT / fname).write_text(fn())
        print(f"wrote docs/framework/{fname}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
