"""Renders the framework's knowledge into Markdown under docs/framework/.

    python -m solutio_framework            # all reports
    python -m solutio_framework rules      # one report: rules | evidence | scenarios | economics
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from . import economics, scenarios

HERE = Path(__file__).resolve().parent
OUT = HERE.parent.parent / "docs" / "framework"
GENERATED = "<!-- Generated by `python -m solutio_framework`. Edit the JSON/Python sources, not this file. -->\n\n"

LEVEL_ORDER = ["global", "eu", "national", "state", "municipal", "field"]
LEVEL_NAME = {"global": "Global", "eu": "European Union", "national": "Brazil (national)", "state": "State (Alagoas)",
              "municipal": "Municipal", "field": "Field (founder's anonymized operational knowledge)"}


def load(name: str) -> dict:
    return json.loads((HERE / name).read_text())


def brl(x: float) -> str:
    if x >= 1e9:
        return f"R$ {x / 1e9:,.2f} bn"
    if x >= 1e6:
        return f"R$ {x / 1e6:,.2f} M"
    return f"R$ {x:,.0f}"


def render_rules() -> str:
    rb = load("rulebook.json")
    lines = [GENERATED, "# Rulebook\n",
             "Each business rule states what Solutio enforces, the legal or institutional source, how it shows up in practice, "
             "and where it is enforced.\n", "| Level | Meaning |", "| --- | --- |"]
    lines += [f"| `{k}` | {v} |" for k, v in rb["enforcement_levels"].items()]
    for domain, title in (("procurement", "Shared purchasing instruments"), ("payment", "Payment obligations and financing")):
        lines += [f"\n## {title}\n"]
        for r in (r for r in rb["rules"] if r["domain"] == domain):
            lines += [f"### {r['id']} · {r['title']}  \n`{r['jurisdiction']}` · enforcement: **{r['enforcement']}**\n",
                      r["rule"] + "\n", "**Sources:** " + "; ".join(r["sources"]) + "\n"]
            if r["practice"]:
                lines.append(f"**Practice:** {r['practice']}\n")
            lines.append(f"**Code:** `{r['code']}`\n")
    return "\n".join(lines)


def render_evidence() -> str:
    ev = load("evidence.json")
    lines = [GENERATED, "# Evidence base\n",
             "Every claim used in the pitch and documentation, with its status and source. "
             "Allegations are labeled as such; nothing here is presented as proven unless a court, law or official dataset says so.\n",
             "| Status | Meaning |", "| --- | --- |"]
    lines += [f"| `{k}` | {v} |" for k, v in ev["status_legend"].items()]
    for level in LEVEL_ORDER:
        items = [i for i in ev["items"] if i["level"] == level]
        if not items:
            continue
        lines += [f"\n## {LEVEL_NAME[level]}\n", "| ID | Claim | Status | Date | Source |", "| --- | --- | --- | --- | --- |"]
        for i in items:
            src = f"[{i['source']}]({i['url']})" if i["url"] else i["source"]
            lines.append(f"| `{i['id']}` | {i['claim']} | {i['status']} | {i['date']} | {src} |")
    return "\n".join(lines)


def _d(d) -> str:
    if d is None:
        return "—"
    return ("✅ " if d.ok else f"⛔ `{d.rule}` ") + d.reason


def render_scenarios() -> str:
    lines = [GENERATED, "# Scenario replays\n",
             "Documented cases replayed through the rules. Where a defect was documented, the same sequence runs under an "
             "illustrative legacy control and under Solutio. Quantities are normalized unless the source gives figures.\n"]
    for s in scenarios.run_all():
        lines += [f"## {s.id} · {s.title}\n", f"*Level:* {LEVEL_NAME[s.level]} · *Evidence:* " +
                  ", ".join(f"`{e}`" for e in s.evidence) + "\n", f"**Question.** {s.question}\n"]
        has_legacy = any(st.legacy is not None for st in s.steps)
        if has_legacy:
            lines += ["| Step | Legacy control | Solutio |", "| --- | --- | --- |"]
            lines += [f"| {st.action} | {_d(st.legacy)} | {_d(st.solutio)} |" for st in s.steps]
        else:
            lines += ["| Step | Solutio |", "| --- | --- |"]
            lines += [f"| {st.action} | {_d(st.solutio)} |" for st in s.steps]
        lines += ["", f"**Finding.** {s.finding}\n"]
    return "\n".join(lines)


def render_economics() -> str:
    a = economics.load_assumptions()
    costs = economics.load_costs()
    lc = economics.lifecycle_costs(costs)
    fx = a["fx"]["brl_per_usd"]["value"]
    lines = [GENERATED, "# Unit economics and scalability\n",
             f"On-chain costs are **measured**, read back from the {len(costs['steps'])} devnet transactions in "
             "[`docs/DEVNET.md`](../DEVNET.md) (`client/devnet-costs.json`). Devnet charges the same base fee per signature as "
             "mainnet; priority fees are excluded. Market anchors come from the evidence base; every other input is an "
             "**assumption** in `framework/solutio_framework/assumptions.json`. These are scenarios, not forecasts.\n",
             "## Measured cost per lifecycle\n",
             "| Lifecycle | Transactions | Fees (lamports) | Rent deposit (lamports) | Compute units |", "| --- | --- | --- | --- | --- |"]
    for v in lc.values():
        lines.append(f"| {v.name} | {v.transactions} | {v.fee_lamports:,} | {v.rent_lamports:,} | {v.compute_units:,} |")
    lines += ["\nRent is a refundable deposit held by the accounts, not a fee. The program does not close settled accounts yet, "
              "so the base case counts it as cost.\n",
              "## Cost per obligation (adhesion + obligation lifecycles), in BRL\n",
              f"Assumed BRL/USD: {fx}.\n", "| SOL price (USD) | Rent counted as cost | Rent recovered (fees only) |", "| --- | --- | --- |"]
    for usd in a["fx"]["usd_per_sol"]["sensitivity"]:
        lines.append(f"| {usd} | R$ {economics.cost_per_obligation_brl(usd):.2f} | R$ {economics.cost_per_obligation_brl(usd, include_rent=False):.4f} |")
    for closing, title in ((False, "Base case: rent counted as cost"), (True, "With a close instruction: rent recovered after settlement")):
        lines += [f"\n## Scenarios · {title}\n",
                  "| Scenario | Volume through Solutio | Obligations/yr | Avg tx/s | Financed volume | Revenue | On-chain cost | Cost / revenue |",
                  "| --- | --- | --- | --- | --- | --- | --- | --- |"]
        for r in economics.scenarios(close_accounts=closing):
            lines.append(f"| {r['scenario']} | {brl(r['volume_brl'])} | {r['obligations_per_year']:,.0f} | {r['tx_per_second_avg']:.3f} | "
                         f"{brl(r['financed_volume_brl'])} | {brl(r['revenue_brl'])} | {brl(r['chain_cost_brl'])} | "
                         f"{100 * r['chain_cost_share_of_revenue']:.1f}% |")
    p = a["pricing"]
    rent = lc["adhesion"].rent_lamports + lc["obligation"].rent_lamports
    rent_share = 100 * rent / (rent + lc["adhesion"].fee_lamports + lc["obligation"].fee_lamports)
    lines += ["\n## Revenue model (assumptions)\n",
              f"- Public bodies pay **nothing**. {p['government_fee_brl']['why']}",
              f"- Financiers pay a verification fee of R$ {p['verification_fee_brl_per_check']['value']:.2f} per check, "
              f"{p['checks_per_financed_obligation']['value']} checks per financed obligation.",
              f"- A take rate of {10_000 * p['take_rate_on_financed_volume']['value']:.0f} bps on financed volume, shared with a licensed financing partner.",
              "\n## What the numbers say\n",
              "1. **Throughput is not the constraint.** Even the national scenario averages well under one transaction per second; "
              "the binding constraint is per-item write serialization, which is the property that enforces the caps.",
              f"2. **Rent dominates on-chain cost.** Rent deposits are {rent_share:.1f}% of the measured cost per obligation; fees are a "
              "fraction of a real. Closing settled accounts turns on-chain cost from tens of percent of revenue into well under 1%.",
              "3. **Revenue comes from financing, not from governments.** The compliance layer is free, which removes the procurement "
              "barrier to adoption; financiers pay because a verified, single-financing receivable lowers their risk.",
              ]
    return "\n".join(lines)


RENDERERS = {"rules": ("RULEBOOK.md", render_rules), "evidence": ("EVIDENCE.md", render_evidence),
             "scenarios": ("SCENARIOS.md", render_scenarios), "economics": ("ECONOMICS.md", render_economics)}


def main(argv: list[str]) -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    names = argv or list(RENDERERS)
    for n in names:
        fname, fn = RENDERERS[n]
        (OUT / fname).write_text(fn())
        print(f"wrote docs/framework/{fname}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
